### PR TITLE
Add 20 second timeout to IDS resolution and more detailed logs (#BRI-7171)

### PR DESCRIPTION
**Pull request by itsjunetime**
@bradtgmurray not necessarily asking for review, just your thoughts on if this is a good idea or could be implemented better

### CODE REVIEW

**Comment by itsjunetime** [comment]
Also see https://linear.app/beeper/issue/BRI-7171#comment-d03210aa

**Review by bradtgmurray — APPROVED** [review]
Timeout and more logs sounds great to me!

**Comment by bradtgmurray** [comment]
How do these logs get plumbed through back to the checkpoint when we try to send a message so we have data on the frequency on each of these cases?

**Comment by itsjunetime** [comment]
It seems that logs in barcelona-mautrix are currently only being sent to mautrix-imessage and oslog, so I don't think they ever make it to any sort of analytics checkpoint. As far as I can tell, we can't really send the checkpoint a success with extra data, so I don't think that notifying the checkpoint of this partial failure is possible. We could add analytics event of some sort (Growthbook? Sentry? What do we use here?), if you think that would be best.

**Comment by bradtgmurray** [comment]
I think this is fine to merge as is and we can figure out how to further improve.

I was just wondering alound how to get more info into the "info" field of a checkpoint when a sent message fails for this reason. ex: https://metabase.beeper-tools.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTQ0MywiZmlsdGVyIjpbImFuZCIsWyJjb250YWlucyIsWyJmaWVsZCIsNDAxNjksbnVsbF0sIlNNUyIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XSxbIj0iLFsiZmllbGQiLDQwMTc3LG51bGxdLCJpbWVzc2FnZWNsb3VkIl0sWyJ0aW1lLWludGVydmFsIixbImZpZWxkIiw0ODY0MSxudWxsXSwtNywiZGF5Iix7ImluY2x1ZGVfY3VycmVudCI6ZmFsc2V9XV19LCJkYXRhYmFzZSI6MTN9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

**Pull request merged**
